// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3.Sensors
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\sensors
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SensorsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.sensors.item collection</summary>
        /// <param name="position">Limit the results to a specific sensors id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder"/></returns>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sensors_%2Did", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.sensors.item collection</summary>
        /// <param name="position">Limit the results to a specific sensors id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("sensors_%2Did", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.SensorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SensorsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.SensorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SensorsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
