// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.Models;
using Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3.Instruments
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\instruments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstrumentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.instruments.item collection</summary>
        /// <param name="position">Limit the results to a specific instruments id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder"/></returns>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("instruments_id", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.instruments.item collection</summary>
        /// <param name="position">Limit the results to a specific instruments id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("instruments_id", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.Item.WithInstruments_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstrumentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/instruments{?limit*,order_by*,page*,sort_order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstrumentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/instruments{?limit*,order_by*,page*,sort_order*}", rawUrl)
        {
        }
        /// <summary>
        /// Provides a list of instruments
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder.InstrumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder.InstrumentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentsResponse>(requestInfo, global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides a list of instruments
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder.InstrumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder.InstrumentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provides a list of instruments
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InstrumentsRequestBuilderGetQueryParameters 
        {
            /// <summary>Change the number of results returned.        e.g. limit=100 will return up to 100 results</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The field by which to order results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Paginate through results. e.g. page=1 will return first page of results</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Sort results ascending or descending. Default ASC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_order")]
            public string? SortOrder { get; set; }
#nullable restore
#else
            [QueryParameter("sort_order")]
            public string SortOrder { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InstrumentsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder.InstrumentsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
