// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.Models;
using Soenneker.OpenAq.OpenApiClient.V3.Providers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3.Providers
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\providers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProvidersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.providers.item collection</summary>
        /// <param name="position">Limit the results to a specific provider by id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder"/></returns>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providers_id", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.OpenAq.OpenApiClient.v3.providers.item collection</summary>
        /// <param name="position">Limit the results to a specific provider by id</param>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("providers_id", position);
                return new global::Soenneker.OpenAq.OpenApiClient.V3.Providers.Item.WithProviders_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProvidersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/providers{?bbox*,coordinates*,countries_id*,iso*,limit*,monitor*,order_by*,page*,parameters_id*,radius*,sort_order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProvidersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/providers{?bbox*,coordinates*,countries_id*,iso*,limit*,monitor*,order_by*,page*,parameters_id*,radius*,sort_order*}", rawUrl)
        {
        }
        /// <summary>
        /// Provides a list of providers
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.ProvidersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.ProvidersResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder.ProvidersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.ProvidersResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder.ProvidersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAq.OpenApiClient.Models.ProvidersResponse>(requestInfo, global::Soenneker.OpenAq.OpenApiClient.Models.ProvidersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides a list of providers
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder.ProvidersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder.ProvidersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provides a list of providers
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProvidersRequestBuilderGetQueryParameters 
        {
            /// <summary>geospatial bounding box of Min X, min Y, max X, max Y in WGS 84 coordinates. Up to 4 decimal points of precision, addtional decimal precision will be truncated to 4 decimal points precision e.g. -77.037,38.907,-77.0,39.910</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bbox")]
            public string? Bbox { get; set; }
#nullable restore
#else
            [QueryParameter("bbox")]
            public string Bbox { get; set; }
#endif
            /// <summary>WGS 84 Coordinate pair in form latitude,longitude. Supports up to 4 decimal points of precision, additional decimal precision will be truncated in the query e.g. 38.9074,-77.0373</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("coordinates")]
            public string? Coordinates { get; set; }
#nullable restore
#else
            [QueryParameter("coordinates")]
            public string Coordinates { get; set; }
#endif
            /// <summary>Limit the results to a specific country or countries by country ID as a single country ID or a comma delimited list of IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("countries_id")]
            public string? CountriesId { get; set; }
#nullable restore
#else
            [QueryParameter("countries_id")]
            public string CountriesId { get; set; }
#endif
            /// <summary>Limit the results to a specific country using ISO 3166-1 alpha-2 code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("iso")]
            public string? Iso { get; set; }
#nullable restore
#else
            [QueryParameter("iso")]
            public string Iso { get; set; }
#endif
            /// <summary>Change the number of results returned.        e.g. limit=100 will return up to 100 results</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Is the location considered a reference monitor?</summary>
            [QueryParameter("monitor")]
            public bool? Monitor { get; set; }
            /// <summary>The field by which to order results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Paginate through results. e.g. page=1 will return first page of results</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters_id")]
            public string? ParametersId { get; set; }
#nullable restore
#else
            [QueryParameter("parameters_id")]
            public string ParametersId { get; set; }
#endif
            /// <summary>Search radius from coordinates as center in meters. Maximum of 25,000 (25km) defaults to 1000 (1km) e.g. radius=1000</summary>
            [QueryParameter("radius")]
            public int? Radius { get; set; }
            /// <summary>Sort results ascending or descending. Default ASC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_order")]
            public string? SortOrder { get; set; }
#nullable restore
#else
            [QueryParameter("sort_order")]
            public string SortOrder { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProvidersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder.ProvidersRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
