// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.V3.Countries;
using Soenneker.OpenAq.OpenApiClient.V3.Instruments;
using Soenneker.OpenAq.OpenApiClient.V3.Licenses;
using Soenneker.OpenAq.OpenApiClient.V3.Locations;
using Soenneker.OpenAq.OpenApiClient.V3.Manufacturers;
using Soenneker.OpenAq.OpenApiClient.V3.Owners;
using Soenneker.OpenAq.OpenApiClient.V3.Parameters;
using Soenneker.OpenAq.OpenApiClient.V3.Providers;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \v3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The countries property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The instruments property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder Instruments
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Instruments.InstrumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenses property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Licenses.LicensesRequestBuilder Licenses
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Licenses.LicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The locations property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Locations.LocationsRequestBuilder Locations
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Locations.LocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manufacturers property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Manufacturers.ManufacturersRequestBuilder Manufacturers
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Manufacturers.ManufacturersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The owners property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Owners.OwnersRequestBuilder Owners
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Owners.OwnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parameters property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Parameters.ParametersRequestBuilder Parameters
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Parameters.ParametersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The providers property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder Providers
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Providers.ProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sensors property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.SensorsRequestBuilder Sensors
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.SensorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
