// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DailyDataSummary : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avg property</summary>
        public double? Avg { get; set; }
        /// <summary>The max property</summary>
        public double? Max { get; set; }
        /// <summary>The median property</summary>
        public double? Median { get; set; }
        /// <summary>The min property</summary>
        public double? Min { get; set; }
        /// <summary>The q02 property</summary>
        public double? Q02 { get; set; }
        /// <summary>The q25 property</summary>
        public double? Q25 { get; set; }
        /// <summary>The q75 property</summary>
        public double? Q75 { get; set; }
        /// <summary>The q98 property</summary>
        public double? Q98 { get; set; }
        /// <summary>The sd property</summary>
        public double? Sd { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.DailyDataSummary"/> and sets the default values.
        /// </summary>
        public DailyDataSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.DailyDataSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.DailyDataSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.DailyDataSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avg", n => { Avg = n.GetDoubleValue(); } },
                { "max", n => { Max = n.GetDoubleValue(); } },
                { "median", n => { Median = n.GetDoubleValue(); } },
                { "min", n => { Min = n.GetDoubleValue(); } },
                { "q02", n => { Q02 = n.GetDoubleValue(); } },
                { "q25", n => { Q25 = n.GetDoubleValue(); } },
                { "q75", n => { Q75 = n.GetDoubleValue(); } },
                { "q98", n => { Q98 = n.GetDoubleValue(); } },
                { "sd", n => { Sd = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("avg", Avg);
            writer.WriteDoubleValue("max", Max);
            writer.WriteDoubleValue("median", Median);
            writer.WriteDoubleValue("min", Min);
            writer.WriteDoubleValue("q02", Q02);
            writer.WriteDoubleValue("q25", Q25);
            writer.WriteDoubleValue("q75", Q75);
            writer.WriteDoubleValue("q98", Q98);
            writer.WriteDoubleValue("sd", Sd);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
