// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class License : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributionRequired property</summary>
        public bool? AttributionRequired { get; set; }
        /// <summary>The commercialUseAllowed property</summary>
        public bool? CommercialUseAllowed { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The modificationAllowed property</summary>
        public bool? ModificationAllowed { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The redistributionAllowed property</summary>
        public bool? RedistributionAllowed { get; set; }
        /// <summary>The shareAlikeRequired property</summary>
        public bool? ShareAlikeRequired { get; set; }
        /// <summary>The sourceUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceUrl { get; set; }
#nullable restore
#else
        public string SourceUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.License"/> and sets the default values.
        /// </summary>
        public License()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.License"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.License CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.License();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributionRequired", n => { AttributionRequired = n.GetBoolValue(); } },
                { "commercialUseAllowed", n => { CommercialUseAllowed = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "modificationAllowed", n => { ModificationAllowed = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "redistributionAllowed", n => { RedistributionAllowed = n.GetBoolValue(); } },
                { "shareAlikeRequired", n => { ShareAlikeRequired = n.GetBoolValue(); } },
                { "sourceUrl", n => { SourceUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("attributionRequired", AttributionRequired);
            writer.WriteBoolValue("commercialUseAllowed", CommercialUseAllowed);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("modificationAllowed", ModificationAllowed);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("redistributionAllowed", RedistributionAllowed);
            writer.WriteBoolValue("shareAlikeRequired", ShareAlikeRequired);
            writer.WriteStringValue("sourceUrl", SourceUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
