// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Location : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Bounds { get; set; }
#nullable restore
#else
        public List<double?> Bounds { get; set; }
#endif
        /// <summary>The coordinates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates? Coordinates { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates Coordinates { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase? Country { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase Country { get; set; }
#endif
        /// <summary>The datetimeFirst property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeFirst { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeFirst { get; set; }
#endif
        /// <summary>The datetimeLast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeLast { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeLast { get; set; }
#endif
        /// <summary>The distance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance? Distance { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance Distance { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The instruments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>? Instruments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase> Instruments { get; set; }
#endif
        /// <summary>The isMobile property</summary>
        public bool? IsMobile { get; set; }
        /// <summary>The isMonitor property</summary>
        public bool? IsMonitor { get; set; }
        /// <summary>The licenses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicense>? Licenses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicense> Licenses { get; set; }
#endif
        /// <summary>The locality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality? Locality { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality Locality { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase Owner { get; set; }
#endif
        /// <summary>The provider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase? Provider { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase Provider { get; set; }
#endif
        /// <summary>The sensors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>? Sensors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase> Sensors { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location"/> and sets the default values.
        /// </summary>
        public Location()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.Location CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.Location();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounds", n => { Bounds = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "coordinates", n => { Coordinates = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates>(global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase>(global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase.CreateFromDiscriminatorValue); } },
                { "datetimeFirst", n => { DatetimeFirst = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "datetimeLast", n => { DatetimeLast = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "distance", n => { Distance = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance>(global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "instruments", n => { Instruments = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>(global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isMobile", n => { IsMobile = n.GetBoolValue(); } },
                { "isMonitor", n => { IsMonitor = n.GetBoolValue(); } },
                { "licenses", n => { Licenses = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicense>(global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicense.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locality", n => { Locality = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality>(global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name>(global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name.CreateFromDiscriminatorValue); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase>(global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase.CreateFromDiscriminatorValue); } },
                { "provider", n => { Provider = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase>(global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase.CreateFromDiscriminatorValue); } },
                { "sensors", n => { Sensors = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>(global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<double?>("bounds", Bounds);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates>("coordinates", Coordinates);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase>("country", Country);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeFirst", DatetimeFirst);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeLast", DatetimeLast);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance>("distance", Distance);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>("instruments", Instruments);
            writer.WriteBoolValue("isMobile", IsMobile);
            writer.WriteBoolValue("isMonitor", IsMonitor);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicense>("licenses", Licenses);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality>("locality", Locality);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name>("name", Name);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase>("owner", Owner);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase>("provider", Provider);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>("sensors", Sensors);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Location_distance : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1? LocationDistanceMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1 LocationDistanceMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_distance();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.LocationDistanceMember1 = new global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(LocationDistanceMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(LocationDistanceMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location_distanceMember1>(null, LocationDistanceMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Location_locality : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1? LocationLocalityMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1 LocationLocalityMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_locality();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.LocationLocalityMember1 = new global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(LocationLocalityMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(LocationLocalityMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location_localityMember1>(null, LocationLocalityMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Location_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1? LocationNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1 LocationNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenAq.OpenApiClient.Models.Location.Location_name();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.LocationNameMember1 = new global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(LocationNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(LocationNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Location_nameMember1>(null, LocationNameMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
