// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LocationFlag : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The datetimeFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeFrom { get; set; }
#endif
        /// <summary>The datetimeTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeTo { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeTo { get; set; }
#endif
        /// <summary>The flagType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.FlagType? FlagType { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.FlagType FlagType { get; set; }
#endif
        /// <summary>The locationId property</summary>
        public int? LocationId { get; set; }
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The sensorIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SensorIds { get; set; }
#nullable restore
#else
        public List<int?> SensorIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag"/> and sets the default values.
        /// </summary>
        public LocationFlag()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datetimeFrom", n => { DatetimeFrom = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "datetimeTo", n => { DatetimeTo = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "flagType", n => { FlagType = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.FlagType>(global::Soenneker.OpenAq.OpenApiClient.Models.FlagType.CreateFromDiscriminatorValue); } },
                { "locationId", n => { LocationId = n.GetIntValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "sensorIds", n => { SensorIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeFrom", DatetimeFrom);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeTo", DatetimeTo);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.FlagType>("flagType", FlagType);
            writer.WriteIntValue("locationId", LocationId);
            writer.WriteStringValue("note", Note);
            writer.WriteCollectionOfPrimitiveValues<int?>("sensorIds", SensorIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
