// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LocationFlag : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The datetimeFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeFrom { get; set; }
#endif
        /// <summary>The datetimeTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject? DatetimeTo { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject DatetimeTo { get; set; }
#endif
        /// <summary>The flagType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.FlagType? FlagType { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.FlagType FlagType { get; set; }
#endif
        /// <summary>The locationId property</summary>
        public int? LocationId { get; set; }
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note? Note { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note Note { get; set; }
#endif
        /// <summary>The sensorIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SensorIds { get; set; }
#nullable restore
#else
        public List<int?> SensorIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag"/> and sets the default values.
        /// </summary>
        public LocationFlag()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datetimeFrom", n => { DatetimeFrom = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "datetimeTo", n => { DatetimeTo = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>(global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject.CreateFromDiscriminatorValue); } },
                { "flagType", n => { FlagType = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.FlagType>(global::Soenneker.OpenAq.OpenApiClient.Models.FlagType.CreateFromDiscriminatorValue); } },
                { "locationId", n => { LocationId = n.GetIntValue(); } },
                { "note", n => { Note = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note>(global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note.CreateFromDiscriminatorValue); } },
                { "sensorIds", n => { SensorIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeFrom", DatetimeFrom);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.DatetimeObject>("datetimeTo", DatetimeTo);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.FlagType>("flagType", FlagType);
            writer.WriteIntValue("locationId", LocationId);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note>("note", Note);
            writer.WriteCollectionOfPrimitiveValues<int?>("sensorIds", SensorIds);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LocationFlag_note : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1? LocationFlagNoteMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1 LocationFlagNoteMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag.LocationFlag_note();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.LocationFlagNoteMember1 = new global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(LocationFlagNoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(LocationFlagNoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationFlag_noteMember1>(null, LocationFlagNoteMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
