// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Location : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Bounds { get; set; }
#nullable restore
#else
        public List<double?> Bounds { get; set; }
#endif
        /// <summary>The coordinates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates? Coordinates { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates Coordinates { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase? Country { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase Country { get; set; }
#endif
        /// <summary>The datetimeFirst property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeFirst? DatetimeFirst { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeFirst DatetimeFirst { get; set; }
#endif
        /// <summary>The datetimeLast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeLast? DatetimeLast { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeLast DatetimeLast { get; set; }
#endif
        /// <summary>The distance property</summary>
        public double? Distance { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The instruments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>? Instruments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase> Instruments { get; set; }
#endif
        /// <summary>The isMobile property</summary>
        public bool? IsMobile { get; set; }
        /// <summary>The isMonitor property</summary>
        public bool? IsMonitor { get; set; }
        /// <summary>The licenses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicenses? Licenses { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicenses Licenses { get; set; }
#endif
        /// <summary>The locality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locality { get; set; }
#nullable restore
#else
        public string Locality { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase Owner { get; set; }
#endif
        /// <summary>The provider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase? Provider { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase Provider { get; set; }
#endif
        /// <summary>The sensors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>? Sensors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase> Sensors { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location"/> and sets the default values.
        /// </summary>
        public Location()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Location"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.Location CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.Location();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounds", n => { Bounds = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "coordinates", n => { Coordinates = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates>(global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase>(global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase.CreateFromDiscriminatorValue); } },
                { "datetimeFirst", n => { DatetimeFirst = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeFirst>(global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeFirst.CreateFromDiscriminatorValue); } },
                { "datetimeLast", n => { DatetimeLast = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeLast>(global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeLast.CreateFromDiscriminatorValue); } },
                { "distance", n => { Distance = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "instruments", n => { Instruments = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>(global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isMobile", n => { IsMobile = n.GetBoolValue(); } },
                { "isMonitor", n => { IsMonitor = n.GetBoolValue(); } },
                { "licenses", n => { Licenses = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicenses>(global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicenses.CreateFromDiscriminatorValue); } },
                { "locality", n => { Locality = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase>(global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase.CreateFromDiscriminatorValue); } },
                { "provider", n => { Provider = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase>(global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase.CreateFromDiscriminatorValue); } },
                { "sensors", n => { Sensors = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>(global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<double?>("bounds", Bounds);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.Coordinates>("coordinates", Coordinates);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CountryBase>("country", Country);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeFirst>("datetimeFirst", DatetimeFirst);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationDatetimeLast>("datetimeLast", DatetimeLast);
            writer.WriteDoubleValue("distance", Distance);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.InstrumentBase>("instruments", Instruments);
            writer.WriteBoolValue("isMobile", IsMobile);
            writer.WriteBoolValue("isMonitor", IsMonitor);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.LocationLicenses>("licenses", Licenses);
            writer.WriteStringValue("locality", Locality);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.EntityBase>("owner", Owner);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.ProviderBase>("provider", Provider);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.SensorBase>("sensors", Sensors);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
