// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MeasurementCoverage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The datetimeFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeFrom? DatetimeFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeFrom DatetimeFrom { get; set; }
#endif
        /// <summary>The datetimeTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeTo? DatetimeTo { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeTo DatetimeTo { get; set; }
#endif
        /// <summary>The expectedCount property</summary>
        public int? ExpectedCount { get; set; }
        /// <summary>The expectedInterval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpectedInterval { get; set; }
#nullable restore
#else
        public string ExpectedInterval { get; set; }
#endif
        /// <summary>The observedCount property</summary>
        public int? ObservedCount { get; set; }
        /// <summary>The observedInterval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObservedInterval { get; set; }
#nullable restore
#else
        public string ObservedInterval { get; set; }
#endif
        /// <summary>The percentComplete property</summary>
        public double? PercentComplete { get; set; }
        /// <summary>The percentCoverage property</summary>
        public double? PercentCoverage { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.MeasurementCoverage"/> and sets the default values.
        /// </summary>
        public MeasurementCoverage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.MeasurementCoverage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.MeasurementCoverage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.MeasurementCoverage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datetimeFrom", n => { DatetimeFrom = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeFrom>(global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeFrom.CreateFromDiscriminatorValue); } },
                { "datetimeTo", n => { DatetimeTo = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeTo>(global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeTo.CreateFromDiscriminatorValue); } },
                { "expectedCount", n => { ExpectedCount = n.GetIntValue(); } },
                { "expectedInterval", n => { ExpectedInterval = n.GetStringValue(); } },
                { "observedCount", n => { ObservedCount = n.GetIntValue(); } },
                { "observedInterval", n => { ObservedInterval = n.GetStringValue(); } },
                { "percentComplete", n => { PercentComplete = n.GetDoubleValue(); } },
                { "percentCoverage", n => { PercentCoverage = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeFrom>("datetimeFrom", DatetimeFrom);
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.CoverageDatetimeTo>("datetimeTo", DatetimeTo);
            writer.WriteIntValue("expectedCount", ExpectedCount);
            writer.WriteStringValue("expectedInterval", ExpectedInterval);
            writer.WriteIntValue("observedCount", ObservedCount);
            writer.WriteStringValue("observedInterval", ObservedInterval);
            writer.WriteDoubleValue("percentComplete", PercentComplete);
            writer.WriteDoubleValue("percentCoverage", PercentCoverage);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
