// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Provider : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bbox property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAq.OpenApiClient.Models.GeoJSON? Bbox { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAq.OpenApiClient.Models.GeoJSON Bbox { get; set; }
#endif
        /// <summary>The datetimeAdded property</summary>
        public DateTimeOffset? DatetimeAdded { get; set; }
        /// <summary>The datetimeFirst property</summary>
        public DateTimeOffset? DatetimeFirst { get; set; }
        /// <summary>The datetimeLast property</summary>
        public DateTimeOffset? DatetimeLast { get; set; }
        /// <summary>The entitiesId property</summary>
        public int? EntitiesId { get; set; }
        /// <summary>The exportPrefix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExportPrefix { get; set; }
#nullable restore
#else
        public string ExportPrefix { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.ParameterBase>? Parameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAq.OpenApiClient.Models.ParameterBase> Parameters { get; set; }
#endif
        /// <summary>The sourceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceName { get; set; }
#nullable restore
#else
        public string SourceName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Provider"/> and sets the default values.
        /// </summary>
        public Provider()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.Provider"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAq.OpenApiClient.Models.Provider CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAq.OpenApiClient.Models.Provider();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bbox", n => { Bbox = n.GetObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.GeoJSON>(global::Soenneker.OpenAq.OpenApiClient.Models.GeoJSON.CreateFromDiscriminatorValue); } },
                { "datetimeAdded", n => { DatetimeAdded = n.GetDateTimeOffsetValue(); } },
                { "datetimeFirst", n => { DatetimeFirst = n.GetDateTimeOffsetValue(); } },
                { "datetimeLast", n => { DatetimeLast = n.GetDateTimeOffsetValue(); } },
                { "entitiesId", n => { EntitiesId = n.GetIntValue(); } },
                { "exportPrefix", n => { ExportPrefix = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.ParameterBase>(global::Soenneker.OpenAq.OpenApiClient.Models.ParameterBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sourceName", n => { SourceName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAq.OpenApiClient.Models.GeoJSON>("bbox", Bbox);
            writer.WriteDateTimeOffsetValue("datetimeAdded", DatetimeAdded);
            writer.WriteDateTimeOffsetValue("datetimeFirst", DatetimeFirst);
            writer.WriteDateTimeOffsetValue("datetimeLast", DatetimeLast);
            writer.WriteIntValue("entitiesId", EntitiesId);
            writer.WriteStringValue("exportPrefix", ExportPrefix);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAq.OpenApiClient.Models.ParameterBase>("parameters", Parameters);
            writer.WriteStringValue("sourceName", SourceName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
