// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.Models;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Days;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Flags;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Measurements;
using Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Years;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\sensors\{sensors_-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sensors_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The days property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Days.DaysRequestBuilder Days
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Days.DaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The flags property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Flags.FlagsRequestBuilder Flags
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Flags.FlagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hours property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.HoursRequestBuilder Hours
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.HoursRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The measurements property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Measurements.MeasurementsRequestBuilder Measurements
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Measurements.MeasurementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The years property</summary>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Years.YearsRequestBuilder Years
        {
            get => new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Years.YearsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sensors_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors/{sensors_%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sensors_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors/{sensors_%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Provides a sensor by sensor ID
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.SensorsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.SensorsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.SensorsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAq.OpenApiClient.Models.SensorsResponse>(requestInfo, global::Soenneker.OpenAq.OpenApiClient.Models.SensorsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides a sensor by sensor ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Sensors_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
