// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAq.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\sensors\{sensors_-id}\hours\daily
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DailyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DailyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors/{sensors_%2Did}/hours/daily{?datetime_from*,datetime_to*,limit*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DailyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/sensors/{sensors_%2Did}/hours/daily{?datetime_from*,datetime_to*,limit*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// Provides a list of daily summaries of hourly data by sensor ID
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.Models.HourlyDataResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.HourlyDataResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAq.OpenApiClient.Models.HourlyDataResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenAq.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAq.OpenApiClient.Models.HourlyDataResponse>(requestInfo, global::Soenneker.OpenAq.OpenApiClient.Models.HourlyDataResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides a list of daily summaries of hourly data by sensor ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAq.OpenApiClient.V3.Sensors.Item.Hours.Daily.DailyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provides a list of daily summaries of hourly data by sensor ID
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DailyRequestBuilderGetQueryParameters 
        {
            /// <summary>From when?</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("datetime_from")]
            public string? DatetimeFrom { get; set; }
#nullable restore
#else
            [QueryParameter("datetime_from")]
            public string DatetimeFrom { get; set; }
#endif
            /// <summary>To when?</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("datetime_to")]
            public string? DatetimeTo { get; set; }
#nullable restore
#else
            [QueryParameter("datetime_to")]
            public string DatetimeTo { get; set; }
#endif
            /// <summary>Change the number of results returned.        e.g. limit=100 will return up to 100 results</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Paginate through results. e.g. page=1 will return first page of results</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
    }
}
#pragma warning restore CS0618
